const news = {
  title:
    "Zero-Covid was supposed to prove China’s supremacy. How did it all go so wrong for Xi Jinping?",
  content:
    "2022 was supposed to be a triumphant year for China and its leader Xi Jinping, as he began his second decade in power with a pledge to restore the nation to greatness. Instead, China had its most difficult year under Xi’s rule as it reeled from his costly zero-Covid policy – from months of overzealous enforcement that crushed the economy and stoked historic public discontent, to a wholesale abandonment so abrupt that left a fragile health system scrambling to cope with an explosion of cases. The chaos and disarray is a stark contrast to the start of the year, when Beijing showcased the success of its Covid containment measures by keeping the coronavirus largely at bay from the Winter Olympics.",
};

const commonWords = [
  // Original redactle
  "a",
  "aboard",
  "about",
  "above",
  "across",
  "after",
  "against",
  "along",
  "amid",
  "among",
  "an",
  "and",
  "around",
  "as",
  "at",
  "because",
  "before",
  "behind",
  "below",
  "beneath",
  "beside",
  "between",
  "beyond",
  "but",
  "by",
  "concerning",
  "considering",
  "despite",
  "down",
  "during",
  "except",
  "following",
  "for",
  "from",
  "if",
  "in",
  "inside",
  "into",
  "is",
  "it",
  "like",
  "minus",
  "near",
  "next",
  "of",
  "off",
  "on",
  "onto",
  "opposite",
  "or",
  "out",
  "outside",
  "over",
  "past",
  "per",
  "plus",
  "regarding",
  "round",
  "save",
  "since",
  "than",
  "the",
  "through",
  "till",
  "to",
  "toward",
  "under",
  "underneath",
  "unlike",
  "until",
  "up",
  "upon",
  "versus",
  "via",
  "was",
  "with",
  "within",
  "without",

  // Redactle Extended
  "all",
  "any",
  "are",
  "be",
  "can",
  "first",
  "may",
  "many",
  "most",
  "much",
  "one",
  "some",
  "that",
  "were",
  "which",
];

const marks = [
  ".",
  ",",
  "-",
  "_",
  "-",
  "(",
  ")",
  "[",
  "]",
  "/",
  "\\",
  "!",
  "?",
  ":",
  ";",
  "'",
  '"',
  "–"
];

const history = [
  {
    guess_id: 123,
    correctCnt: 5,
    guessesCnt: 100,
    news_id: 12323,
    newsTitle: "aakdsa ddksdos ",
    newsDate: "2022-12-15",
    newsLink: "https://www.euronews.com/tag/die-linke",
  },
];

export { news, marks, commonWords, history };
